# Generated by Django 6.0.6 on 2026-07-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="search_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
